const subscriptStyle: object = {
    seckill_subscript_location: 'top-left',
    text_or_icon_color: '#fff',
    text_or_icon_size: 12,
    img_width: 20,
    img_height: 20,
    direction: '90deg',
    color_list: [{ color: '#FF7607', color_percentage: undefined }],
    background_img_style: '2',
    background_img: [] as uploadList[],
    margin: 0,
    margin_top: 0,
    margin_bottom: 0,
    margin_left: 0,
    margin_right: 0,
    radius: 4,
    radius_top_left: 4,
    radius_top_right: 4,
    radius_bottom_left: 4,
    radius_bottom_right: 4,
    padding: 0,
    padding_top: 0,
    padding_bottom: 0,
    padding_left: 10,
    padding_right: 10,
    box_shadow_color: '',
    box_shadow_x: 0,
    box_shadow_y: 0,
    box_shadow_blur: 0,
    box_shadow_spread: 0,
};

export default subscriptStyle;